### ISSUE TITLE
Generating random sequences when encoding the graphs

### ISSUE THREAD

**Issue by nbellor** [marcopodda/grapher#2]
In grapher/dataset/graph.py you define encode_graph(G, order) which encodes the graph before being fed to the Neural Network depending on the order (fixed/random) and algorithm (bfs/dfs) selected. When you define 'seq' within this function you do so taking into account that some of the methods are random, but this list (seq) is not used to modify the output of the function, meaning that the sequence will be the same even if the 'random' methods are being used.

Is this behavior intended or am I misinterpreting the code?

Thank you,
Nicolas Bello

```
def encode_graph(G, order):
    G = max_connected_comp(G)
    mapping = {n: i for (i, n) in enumerate(G.nodes(), 3)}
    G = nx.relabel_nodes(G, mapping)

    nodes_list = list(G.nodes())

    if order == "bfs-fixed":
        start_node = min(nodes_list)
        seq = bfs_order(G, start_id=start_node)
    elif order == "bfs-random":
        start_node = np.random.choice(nodes_list)
        seq = bfs_order(G, start_id=start_node)
    elif order == "dfs-random":
        start_node = np.random.choice(nodes_list)
        seq = dfs_order(G, start_id=start_node)
    elif order == "dfs-fixed":
        start_node = min(nodes_list)
        seq = dfs_order(G, start_id=start_node)
    elif order == "random":
        seq = nodes_list
        np.random.shuffle(seq)
    elif order == "smiles":
        # this is the case of SMILES ordering, which
        # for chemical datasets is given by default
        seq = nodes_list
    else:
        raise ValueError

    edges = G.edges()
    if order != "smiles":
        edges = sorted(edges)

    return list(zip(*edges))

**Comment by marcopodda** [comment]
Hello Nicolas,
you are absolutely correct, it makes no sense. If I look at the commit history I see that in the first commit everything was correct, I don't know what went wrong in the following commits, probably I was trying to clean up the code or whatever and I introduced the bug. If you pull now that part should be fixed. 

Thanks for spotting the bug, and let me know if something's still not working!
